"""Data models and core types for Binance Futures Trading Bot."""

from dataclasses import dataclass, field
from typing import Optional, Dict


@dataclass
class Candle:
    """Represents a single candlestick/kline with OHLCV data.
    
    Attributes:
        timestamp: Unix timestamp in milliseconds
        open: Opening price
        high: Highest price during the period
        low: Lowest price during the period
        close: Closing price
        volume: Trading volume during the period
    """
    timestamp: int
    open: float
    high: float
    low: float
    close: float
    volume: float


@dataclass
class Position:
    """Represents an open trading position.
    
    Attributes:
        symbol: Trading pair symbol (e.g., "BTCUSDT")
        side: Position direction ("LONG" or "SHORT")
        entry_price: Price at which position was entered
        quantity: Position size in base currency
        leverage: Leverage multiplier used
        stop_loss: Initial stop-loss price
        trailing_stop: Current trailing stop price
        entry_time: Unix timestamp when position was opened
        unrealized_pnl: Current unrealized profit/loss
    """
    symbol: str
    side: str  # "LONG" or "SHORT"
    entry_price: float
    quantity: float
    leverage: int
    stop_loss: float
    trailing_stop: float
    entry_time: int
    unrealized_pnl: float = 0.0


@dataclass
class Trade:
    """Represents a completed trade with entry and exit details.
    
    Attributes:
        symbol: Trading pair symbol
        side: Trade direction ("LONG" or "SHORT")
        entry_price: Price at which trade was entered
        exit_price: Price at which trade was exited
        quantity: Trade size in base currency
        pnl: Realized profit/loss in quote currency
        pnl_percent: Profit/loss as percentage of entry value
        entry_time: Unix timestamp when trade was entered
        exit_time: Unix timestamp when trade was exited
        exit_reason: Reason for exit ("STOP_LOSS", "TRAILING_STOP", "SIGNAL_EXIT", "PANIC")
    """
    symbol: str
    side: str
    entry_price: float
    exit_price: float
    quantity: float
    pnl: float
    pnl_percent: float
    entry_time: int
    exit_time: int
    exit_reason: str


@dataclass
class Signal:
    """Represents a trading signal generated by the strategy.
    
    Attributes:
        type: Signal type ("LONG_ENTRY", "SHORT_ENTRY", "EXIT")
        timestamp: Unix timestamp when signal was generated
        price: Price at which signal was generated
        indicators: Snapshot of indicator values at signal generation
        confidence: Signal confidence from multi-timeframe analysis (0.0-1.0)
        symbol: Trading pair symbol (optional, defaults to None for backward compatibility)
    """
    type: str  # "LONG_ENTRY", "SHORT_ENTRY", "EXIT"
    timestamp: int
    price: float
    indicators: Dict[str, float] = field(default_factory=dict)
    confidence: float = 1.0  # Default to 1.0 for backward compatibility
    symbol: Optional[str] = None  # Optional symbol for multi-symbol support


@dataclass
class IndicatorState:
    """Holds all technical indicator values for the current market state.
    
    Attributes:
        vwap_15m: VWAP on 15-minute timeframe
        vwap_1h: VWAP on 1-hour timeframe
        weekly_anchor_time: Timestamp of weekly anchor point for VWAP
        squeeze_value: Current squeeze momentum value
        squeeze_color: Current squeeze color ("green", "maroon", "blue", "gray")
        is_squeezed: Whether market is currently in a squeeze
        previous_squeeze_color: Previous squeeze color for detecting releases
        adx: Current ADX value
        trend_1h: 1-hour trend direction ("BULLISH", "BEARISH", "NEUTRAL")
        trend_15m: 15-minute trend direction
        atr_15m: ATR on 15-minute timeframe
        atr_1h: ATR on 1-hour timeframe
        rvol: Current relative volume
        current_price: Current market price
        price_vs_vwap: Price position relative to VWAP ("ABOVE", "BELOW")
    """
    vwap_15m: float = 0.0
    vwap_1h: float = 0.0
    weekly_anchor_time: int = 0
    squeeze_value: float = 0.0
    squeeze_color: str = "gray"
    is_squeezed: bool = False
    previous_squeeze_color: str = "gray"
    adx: float = 0.0
    trend_1h: str = "NEUTRAL"
    trend_15m: str = "NEUTRAL"
    atr_15m: float = 0.0
    atr_1h: float = 0.0
    rvol: float = 0.0
    current_price: float = 0.0
    price_vs_vwap: str = "BELOW"


@dataclass
class PerformanceMetrics:
    """Performance metrics for backtest results and live trading analysis.
    
    Attributes:
        total_trades: Total number of trades executed
        winning_trades: Number of profitable trades
        losing_trades: Number of losing trades
        win_rate: Percentage of winning trades
        total_pnl: Total profit/loss in quote currency
        total_pnl_percent: Total profit/loss as percentage
        roi: Return on investment percentage
        max_drawdown: Maximum drawdown in quote currency
        max_drawdown_percent: Maximum drawdown as percentage
        profit_factor: Ratio of gross profit to gross loss
        sharpe_ratio: Risk-adjusted return metric
        average_win: Average profit per winning trade
        average_loss: Average loss per losing trade
        largest_win: Largest single winning trade
        largest_loss: Largest single losing trade
        average_trade_duration: Average trade duration in seconds
    """
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    win_rate: float = 0.0
    total_pnl: float = 0.0
    total_pnl_percent: float = 0.0
    roi: float = 0.0
    max_drawdown: float = 0.0
    max_drawdown_percent: float = 0.0
    profit_factor: float = 0.0
    sharpe_ratio: float = 0.0
    average_win: float = 0.0
    average_loss: float = 0.0
    largest_win: float = 0.0
    largest_loss: float = 0.0
    average_trade_duration: int = 0


@dataclass
class TimeframeData:
    """Data for a single timeframe analysis.
    
    Attributes:
        trend: Trend direction ("BULLISH", "BEARISH", "NEUTRAL")
        momentum: Momentum value (float)
        volatility: Volatility measure (ATR)
        volume_trend: Volume trend ("INCREASING", "DECREASING", "STABLE")
    """
    trend: str  # "BULLISH", "BEARISH", "NEUTRAL"
    momentum: float
    volatility: float
    volume_trend: str  # "INCREASING", "DECREASING", "STABLE"


@dataclass
class TimeframeAnalysis:
    """Complete multi-timeframe analysis result.
    
    Attributes:
        timeframe_5m: Analysis for 5-minute timeframe
        timeframe_15m: Analysis for 15-minute timeframe
        timeframe_1h: Analysis for 1-hour timeframe
        timeframe_4h: Analysis for 4-hour timeframe
        alignment_score: Number of aligned timeframes (0-4)
        confidence: Signal confidence (0.0-1.0)
        overall_direction: Overall trend direction ("BULLISH", "BEARISH", "NEUTRAL")
    """
    timeframe_5m: Optional['TimeframeData']
    timeframe_15m: Optional['TimeframeData']
    timeframe_1h: Optional['TimeframeData']
    timeframe_4h: Optional['TimeframeData']
    alignment_score: int  # 0-4
    confidence: float  # 0.0-1.0
    overall_direction: str  # "BULLISH", "BEARISH", "NEUTRAL"


@dataclass
class VolumeProfile:
    """Volume profile data showing volume distribution at price levels.
    
    Attributes:
        price_levels: List of price levels (bin centers)
        volumes: List of volumes at each price level
        poc: Point of Control (price level with highest volume)
        vah: Value Area High (upper bound of 70% volume area)
        val: Value Area Low (lower bound of 70% volume area)
        total_volume: Total volume across all price levels
        timestamp: Unix timestamp when profile was calculated
    """
    price_levels: List[float]
    volumes: List[float]
    poc: float  # Point of Control
    vah: float  # Value Area High
    val: float  # Value Area Low
    total_volume: float
    timestamp: int


@dataclass
class RegimeParameters:
    """Parameters for trading in a specific market regime.
    
    Attributes:
        regime: Current regime classification
        stop_multiplier: ATR multiplier for stop-loss
        threshold_multiplier: Multiplier for indicator thresholds
        position_size_multiplier: Multiplier for position sizing
        strategy_type: Strategy to use in this regime
    """
    regime: str
    stop_multiplier: float
    threshold_multiplier: float
    position_size_multiplier: float
    strategy_type: str  # "TREND_FOLLOWING", "MEAN_REVERSION", "NONE"


@dataclass
class PortfolioMetrics:
    """Portfolio-level performance metrics.
    
    Attributes:
        total_value: Total portfolio value in quote currency
        total_pnl: Total profit/loss across all symbols
        per_symbol_pnl: PnL breakdown by symbol
        correlation_matrix: Correlation coefficients between symbols
        total_risk: Total portfolio risk as percentage
        diversification_ratio: Measure of portfolio diversification
    """
    total_value: float
    total_pnl: float
    per_symbol_pnl: Dict[str, float]
    correlation_matrix: Dict[tuple, float]
    total_risk: float
    diversification_ratio: float
